apiVersion: v1
kind: Pod
metadata:
  name: wik-dps-tp04-1
spec:
  containers:
  - name: wik-dps-tp02
    image: registry.cluster.wik.cloud/public/echo
    env:
    - name: PING_LISTEN_PORT
      value: "80"
    ports:
    - containerPort: 80