apiVersion: apps/v1
kind: Deployment
metadata:
  name: wik-dps-tp04-3
  labels:
    app : wik-dps-tp04-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wik-dps-tp04-3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: wik-dps-tp04-3
    spec:
      containers:
      - name: wik-dps-tp04-3
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 80
        env:
        - name: PING_LISTEN_PORT 
          value : "80"